### ISSUE TITLE
Broken Instance Links to Hidden Modules

### ISSUE THREAD

**Issue by m00ngoose** [haskell/haddock#1046] opened 2019-03-25 12:00 UTC
Auto-generated instance links to hidden modules are not valid, see https://github.com/haskell/time/issues/114 for an example. Maintainer says that Haddock is at fault.

I suggest there that it links directly to the source code?

**Comment by harpocrates** [comment] 2019-03-25 12:39
Thanks for reporting!

This is indeed a bug in Haddock, and it's already been fixed in the `ghc-head` branch (and the `ghc-8.8` branch too I think). Let's not close until we can confirm with docs that are released though - this is quite a nasty bug and I'm not sure we have a regression test for it either.

**Comment by harpocrates** [comment] 2020-03-28 01:51
Definitely fixed, since https://hackage.haskell.org/package/time-1.10/docs/Data-Time-LocalTime.html now has the right instance link.

**Closed by harpocrates** 2020-03-28 01:51 UTC
Labels: bug
