### ISSUE TITLE
RFE - meta modules should be ignored

### ISSUE THREAD

**Issue by victoredwardocallaghan** [haskell/haddock#370] opened 2015-03-04 22:19 UTC
G'day,

Consider the following:

'''
{-# OPTIONS_HADDOCK hide, prune #-}
module Foo (module X) where

import Foo.Bar as X
import Foo.Zar as X
'''

Haddock throws the following warning:
"Warning: foo-0.1.0.0:Foo: Could not find documentation for exported module: X"

However, clearly here X is a meta module to make things neat. Could we make Haddock respect this tricky please?

Kind Regards,
Edward O'Callaghan.

**Comment by Fuuzetsu** [comment] 2015-03-05 07:45
This is duplicate of issue #121 so I am closing. It's good to see interest in it however.

**Closed by Fuuzetsu** 2015-03-05 07:45 UTC
