### ISSUE TITLE
Homepage https://www.haskell.org/haddock/ is outdated.

### ISSUE THREAD

**Issue by jiegec** [haskell/haddock#503] opened 2016-05-14 23:19 UTC
The releases etc are outdated.

**Comment by jiegec** [comment] 2016-05-14 23:23
The new releases 2.17.x are not on Hackage.

**Comment by sjakobi** [comment] 2017-02-17 22:31
Duplicate of https://github.com/haskell/haddock/issues/360 :/

**Closed** 2017-02-17 23:46 UTC
