### ISSUE TITLE
SIGSEGV when building haddocks for haskell-src-exts with hyperlinked sources

### ISSUE THREAD

**Issue by qrilka** [haskell/haddock#986] opened 2018-12-24 12:30 UTC
The original ticket is https://github.com/haskell-suite/haskell-src-exts/issues/418 opening issue for Haddock on suggesttion from @mpickering

**Comment by harpocrates** [comment] 2018-12-24 13:21
Duplicate of #837.

In a nutshell: this is fixed starting in 8.6.1, but not on any of 8.4.{1,2,3,4}.

**Closed by harpocrates** 2018-12-24 13:21 UTC

**Comment by qrilka** [comment] 2018-12-24 14:17
LTS-13.0 does the trick, thanks
