### ISSUE TITLE
documentation and website News shows 2.15

### ISSUE THREAD

**Issue by simonmichael** [haskell/haddock#440] opened 2015-08-26 16:06 UTC
These should be updated for the current release.

http://hackage.haskell.org/package/haddock -> Home Page -> News
http://hackage.haskell.org/package/haddock -> Home Page -> Documentation -> Online (HTML)

**Comment by Fuuzetsu** [comment] 2015-08-26 23:29
Basically a duplicate of #360 , we'll most likely scrap the site. Maybe during weekend if time allows.

**Closed by Fuuzetsu** 2015-08-26 23:29 UTC
