### ISSUE TITLE
LiftedRep noise in haddock output

### ISSUE THREAD

**Issue by jchia** [haskell/haddock#713] opened 2017-12-06 00:12 UTC
GHC version: 8.2.2
platform: stack 1.6 on Arch Linux with nightly-2017-11-27 resolver

How to repro:
`stack haddock` from a stack project that has `base` in its cabal build-depends.

Result:
Haddock output has instances involving `LiftedRep` when it shouldn't. E.g. Functor & Applicative, where LiftedRep is not even mentioned in the source code:
https://www.stackage.org/haddock/nightly-2017-11-27/base-4.10.1.0/Data-Functor.html
https://www.stackage.org/haddock/nightly-2017-11-27/base-4.10.1.0/Control-Applicative.html

**Comment by harpocrates** [comment] 2017-12-06 00:43
Possible duplicate of https://github.com/haskell/haddock/issues/544?

**Comment by alexbiehl** [comment] 2017-12-06 05:15
@RyanGlScott does your recent work on kind signature rendering address this?

**Comment by RyanGlScott** [comment] 2017-12-06 14:10
Indeed it does! Here's what the `Functor ((->) r)` instance looks like on Haddock HEAD:

![haddock](https://user-images.githubusercontent.com/2364661/33665557-570f33a6-da65-11e7-8446-db99231fba77.png)

**Comment by alexbiehl** [comment] 2017-12-06 14:43
Nice! I will close this duplicate then. Thanks for reporting.

**Closed by alexbiehl** 2017-12-06 14:43 UTC
