### ISSUE TITLE
Rendered haddock of `Eq` and `Ord` classes are missing class methods

### ISSUE THREAD

**Issue by christiaanb** [haskell/haddock#549] opened 2016-08-22 13:44 UTC
The rendered haddock (included in the GHC 8.0.1 release) for the `Eq` and `Ord` classes are missing:
- Their class methods
- Their source links

See:

​http://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Eq.html#t:Eq
​http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#t:Eq
​http://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Ord.html#t:Ord
​http://hackage.haskell.org/package/base-4.9.0.0/docs/Prelude.html#t:Ord

Other (deriviable) classes, for example Show, or Enum, do not have these problems.

I've also reported this as a GHC issue: https://ghc.haskell.org/trac/ghc/ticket/12519

**Comment by k-bx** [comment] 2016-09-19 10:46
In https://github.com/haskell/haddock/issues/552 duplicate I've provided a repo with easy reproduction steps.

**Comment by niteria** [comment] 2016-09-20 14:41
I have a fix here, but due to poor internet it's difficult for me to commit/send a pull request. https://ghc.haskell.org/trac/ghc/ticket/12519#comment:6

**Comment by ysangkok** [comment] 2017-02-02 01:49
I think this was fixed with https://github.com/haskell/haddock/commit/240bc38b94ed2d0af27333b23392d03eeb615e82 ?

**Closed** 2017-07-03 06:46 UTC
