### ISSUE TITLE
Some instances not shown 

### ISSUE THREAD

**Issue by josefs** [haskell/haddock#695] opened 2017-10-29 10:49 UTC
Look at the documentation for the type `SFunArray` in the package SBV:
https://hackage.haskell.org/package/sbv-7.3/docs/Data-SBV.html#t:SFunArray

The documentation for `SFunArray` is missing the instance for the class `SymArray` which is defined here:
https://hackage.haskell.org/package/sbv-7.3/docs/src/Data.SBV.Core.Model.html#line-1436

Haddock clearly processes the module `Data.SBV.Core.Model` where the instance is declared so I'm at a loss as to why this instance is not reported.

**Comment by alexbiehl** [comment] 2017-10-29 12:35
Thanks for the report @josefs. 

Just a wild guess: @duog IIRC implemented `getNameToInstancesIndex` in GHC could it be possible it misses some instances for whatever reasons?

**Comment by harpocrates** [comment] 2018-01-05 20:43
I've confirmed that the output of `getNameToInstancesIndex` is missing the `SymArray` instance.

**Comment by alexbiehl** [comment] 2018-01-05 21:03
Alec, `getNameToInstancesIndex` looks more or less innocent. Any idea why GHC would miss it?

**Comment by harpocrates** [comment] 2018-01-06 05:19
Alright. I finally managed to find some time to actually look at this in more detail. This is just a regular orphan instance problem. I'm unsure what we currently expect Haddock to do, but I'm a bit disappointed:

```haskell
-- Main.hs
module Main (Class(..), Data(..), main) where

import Data
import Orphan

main = pure ()
```


```haskell
-- Orphan.hs
module Orphan where

import Data

instance Class Data
```


```haskell
-- Data.hs
module Data where

class Class a
data Data
```

Produces for `Main`:

<img width="238" alt="screen shot 2018-01-05 at 9 14 20 pm" src="https://user-images.githubusercontent.com/10766081/34636760-7442cf2c-f25d-11e7-9ee3-2193248c38b3.png">

**Comment by harpocrates** [comment] 2018-01-06 08:17
I'm starting to understand what is happening, and I think I've got a fix. It looks like the issue is around the `instIsVisible` check of `getNameToInstancesIndex`. Disabling this check, we get back our instance.

However, we probably do not want to disable this check in general - we may end up with instances that have no reason to be displayed (for example, an instance for a class defined in the project but never exported)! The first argument that `instIsVisible` expects is a set of modules which are visible. When determining if an orphan instance is visible, it checks for membership in that set. Right now, that set always ends up being a singleton containing one garbage GHCi module (this is due to using `runTcInteractive`).  We want that set of modules to match the set of modules Haddock is processing!

All in all, that means

  * updating `getNameToInstancesIndex` to take an argument which is the set of modules being processed. 

 ```haskell
 -- | Retrieve all type and family instances in the environment, indexed
 -- by 'Name'. Each name's lists will contain every instance in which that name
 -- is mentioned in the instance head.
 getNameToInstancesIndex :: GhcMonad m
   => [Module] -> m (Messages, Maybe (NameEnv ([ClsInst], [FamInst])))            -- !!!!
 getNameToInstancesIndex visible_mods = do                                        -- !!!!
   hsc_env <- getSession
   liftIO $ runTcInteractive hsc_env $
     do { loadUnqualIfaces hsc_env (hsc_IC hsc_env)
        ; InstEnvs {ie_global, ie_local, ie_visible} <- tcGetInstEnvs
        ; let visible_mods_set = mkModuleSet visible_mods                         -- !!!!
        ; (pkg_fie, home_fie) <- tcGetFamInstEnvs
        -- We use Data.Sequence.Seq because we are creating left associated
        -- mappends.
        -- cls_index and fam_index below are adapted from TcRnDriver.lookupInsts
        ; let cls_index = Map.fromListWith mappend
                  [ (n, Seq.singleton ispec)
                  | ispec <- instEnvElts ie_local ++ instEnvElts ie_global
                  , instIsVisible visible_mods_set ispec                          -- !!!!
                  , n <- nameSetElemsStable $ orphNamesOfClsInst ispec
                  ]
        ; let fam_index = Map.fromListWith mappend
                  [ (n, Seq.singleton fispec)
                  | fispec <- famInstEnvElts home_fie ++ famInstEnvElts pkg_fie
                  , n <- nameSetElemsStable $ orphNamesOfFamInst fispec
                  ]
        ; return $ mkNameEnv $
            [ (nm, (toList clss, toList fams))
            | (nm, (clss, fams)) <- Map.toList $ Map.unionWith mappend
                (fmap (,Seq.empty) cls_index)
                (fmap (Seq.empty,) fam_index)
            ] }
 ```

  * passing in that set of modules in `attachInstances`:

```haskell
attachInstances :: ExportInfo -> [Interface] -> InstIfaceMap -> Ghc [Interface]
attachInstances expInfo ifaces instIfaceMap = do
  (_msgs, mb_index) <- getNameToInstancesIndex (map ifaceMod ifaces)             -- !!!!
  mapM (attach $ fromMaybe emptyNameEnv mb_index) ifaces
  where
    -- TODO: take an IfaceMap as input
    ifaceMap = Map.fromList [ (ifaceMod i, i) | i <- ifaces ]

    attach index iface = do
      newItems <- mapM (attachToExportItem index expInfo iface ifaceMap instIfaceMap)
                       (ifaceExportItems iface)
      let orphanInstances = attachOrphanInstances expInfo iface ifaceMap instIfaceMap (ifaceInstances iface)
      return $ iface { ifaceExportItems = newItems
                     , ifaceOrphanInstances = orphanInstances
}
```

With these changes, I get 

<img width="249" alt="screen shot 2018-01-06 at 12 13 06 am" src="https://user-images.githubusercontent.com/10766081/34637959-6d123490-f276-11e7-8bd7-a785501f8630.png">

I'll do the actual Haddock PR / GHC patch work tomorrow.

Does this sound like it makes sense? @alexbiehl @duog

**Comment by alexbiehl** [comment] 2018-01-06 09:54
Great! That sounds reasonable! 

Is it enough to pass the modules from `ifaces` or do we need to also consider passing the modules from the installed interfaces?

**Comment by alexbiehl** [comment] 2018-01-06 09:54
(and let's see that we get this fix into ghc-8.4.1) *fingers crossed* @bgamari

**Comment by harpocrates** [comment] 2018-01-06 18:27
Here is the PR: https://github.com/haskell/haddock/pull/724

**Comment by duog** [comment] 2018-01-07 21:30
Looks good to me, thanks fixing my mess.

**Comment by gbaz** [comment] 2018-02-05 06:39
with that pr merged, should this be closed?

**Comment by alexbiehl** [comment] 2018-02-05 06:42
(@gbaz yes)

**Closed by alexbiehl** 2018-02-05 06:42 UTC
