### ISSUE TITLE
Failure generating haddocks for ghc-prim on ghc-8.4

### ISSUE THREAD

**Issue by bgamari** [haskell/haddock#760] opened 2018-02-18 21:36 UTC
Using haddock 5141e4b76af8462e49abdf48e44bb9cddb183383 on bgamari/ghc@ffaef38b6b07dd6628867fff154e689873e2b0fd (the current state of the `ghc-8.4` branch) I am seeing the following failure while building documentation for `ghc-prim`:
```
"/home/ben/ghc/ghc-8.4/inplace/bin/haddock" --verbosity=0 --odir="libraries/ghc-prim/dist-install/doc/html/ghc-prim" --no-tmp-comp-dir --dump-interface=libraries/ghc-prim/dist-install/doc/html/ghc-prim/ghc-prim.haddock --html --hoogle --quickjump --title="ghc-prim-0.5.2.0: GHC primitives" --prologue="libraries/ghc-prim/dist-install/haddock-prologue.txt" --optghc="-D__HADDOCK_VERSION__=2190"   --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-O0 --optghc=-H64m --optghc=-Wall --optghc=-fllvm-fill-undef-with-garbage --optghc=-Werror --optghc=-this-unit-id --optghc=ghc-prim-0.5.2.0 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/ghc-prim/. --optghc=-ilibraries/ghc-prim/dist-install/build --optghc=-Ilibraries/ghc-prim/dist-install/build --optghc=-ilibraries/ghc-prim/dist-install/build/./autogen --optghc=-Ilibraries/ghc-prim/dist-install/build/./autogen --optghc=-Ilibraries/ghc-prim/. --optghc=-optP-include --optghc=-optPlibraries/ghc-prim/dist-install/build/./autogen/cabal_macros.h --optghc=-package-id --optghc=rts --optghc=-this-unit-id --optghc=ghc-prim --optghc=-XHaskell2010 --optghc=-O --optghc=-dno-debug-output --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-Wno-trustworthy-safe --optghc=-Wno-deprecated-flags --optghc=-Wnoncanonical-monad-instances --optghc=-odir --optghc=libraries/ghc-prim/dist-install/build --optghc=-hidir --optghc=libraries/ghc-prim/dist-install/build --optghc=-stubdir --optghc=libraries/ghc-prim/dist-install/build --source-module=src/%{MODULE/./-}.html --source-entity=src/%{MODULE/./-}.html#%{NAME}   libraries/ghc-prim/./GHC/CString.hs  libraries/ghc-prim/./GHC/Classes.hs  libraries/ghc-prim/./GHC/Debug.hs  libraries/ghc-prim/./GHC/IntWord64.hs  libraries/ghc-prim/./GHC/Magic.hs  libraries/ghc-prim/dist-install/build/GHC/PrimopWrappers.hs  libraries/ghc-prim/./GHC/Tuple.hs  libraries/ghc-prim/./GHC/Types.hs libraries/ghc-prim/dist-install/build/autogen/GHC/Prim.hs  +RTS -t"libraries/ghc-prim/dist-install/haddock.t" --machine-readable
Warning: Couldn't find .haddock for export TYPE
haddock: internal error: Create: 
neInt
eqInt :: Int -> Int -> Bool

CallStack (from HasCallStack):
  error, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:736:57 in main:Haddock.Interface.Create
libraries/ghc-prim/ghc.mk:4: recipe for target 'libraries/ghc-prim/dist-install/doc/html/ghc-prim/ghc-prim.haddock' failed
```

This was with the following patch applied,
```patch
diff --git a/haddock-api/src/Haddock/Interface/Create.hs b/haddock-api/src/Haddock/Interface/Create.hs
index f218853b..b87c7a80 100644
--- a/haddock-api/src/Haddock/Interface/Create.hs
+++ b/haddock-api/src/Haddock/Interface/Create.hs
@@ -733,7 +733,8 @@ availExportItem is_sig modMap thisMod semMod warnings exportedNames
                   L loc (SigD sig) ->
                     -- fromJust is safe since we already checked in guards
                     -- that 't' is a name declared in this declaration.
-                    let newDecl = L loc . SigD . fromJust $ filterSigNames (== t) sig
+                    let newDecl = L loc . SigD . maybe (error $  unlines ["Create: ", pretty dflags t, pretty dflags sig]) id 
+                                $ filterSigNames (== t) sig
                     in availExportDecl avail newDecl docs_
 
                   L loc (TyClD cl@ClassDecl{}) -> do
```

**Comment by alexbiehl** [comment] 2018-02-19 13:51
This was accidentally introduced in https://github.com/haskell/haddock/commit/4b4733a05c7bf35d98ed82f2a62d4771db1fb788. 

The issue is fixed by 6d62c5b79d0f3ce975c087b5176ee53d62122d86 (and subsequently d66092ee99639de628dbc4fce8a9936875f47d8c).

**Closed by alexbiehl** 2018-02-19 13:51 UTC
