### ISSUE TITLE
haddock error if reexport pattern of data family instance.

### ISSUE THREAD

**Issue by YoshikuniJujo** [haskell/haddock#1222] opened 2020-08-06 03:42 UTC
## Steps to reproduce

src/A.hs

```haskell:src/A.hs
{-# LANGUAGE PatternSynonyms #-}
module A (pattern BarUnit) where import B
```

src/B.hs

```haskell:src/B.hs
{-# LANGUAGE PatternSynonyms, TypeFamilies #-}
module B (pattern BarUnit) where

class Foo a where data Bar a
instance Foo () where data Bar () = BarUnit
```

```
% stack haddock
...
haddock: panic! (the 'impossible' happened)
  (GHC version 8.10.1:
        extractDecl

Ambigous decl for BarUnit in class:
   class Foo a where
      data Bar a
Matches:
   [] []
Call stack:
   CallStack (from HasCallStack):
     callStackDoc, called at compiler/utils/Outputable.hs:1179:37 in ghc:Outputable
     pprPanic, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1078:16 in main:Haddock.Interface.Create

Please report this as a GHC bug: https://www.haskell.org/ghc/reportabug

...
```

## Environment

* GHC: version 8.10.1
* Stackage: nightly-2020-08-03

## Sample code

https://github.com/YoshikuniJujo/test_haskell/tree/master/bug_report/bug-pattern-synonym-haddock

**Comment by emiflake** [comment] 2021-01-05 18:51
Hi, thanks for submitting an issue and supplying sample code! 

This issue looks like it's a duplicate of #1067 (although not identical) and is fixed by 5bc5016a14bc872a8315cddc629f8171a9ccd62e. Bumping your stackage snapshot will fix it locally for you too.

Closing it for now!

**Closed by emiflake** 2021-01-05 18:51 UTC
