### ISSUE TITLE
parse failure: function param docs inside a record

### ISSUE THREAD

**Issue by shapr** [haskell/haddock#1170] opened 2020-04-23 15:10 UTC
Hello! I think this is a minimal test case. 

I don't know if it's an already known bug. I looked through a few pages of github issues but quickly gave up looking for a collection of parse failures.

I'm likely to submit more parse failures soon, is there a collection of known parse failures I could reference?
 
```
module Main where

-- | works fine
functionOne
  :: Int -- ^ int
  -> Maybe Int -- ^ works fine
functionOne = undefined

-- | function parameter docs inside a data declaration fail to parse
data Thing = Thing
    { -- | header
      functionThing
      :: Int -- ^ first
      -> Maybe Int -- ^ THIS FAILS
    }

main = print "hi"
```

**Comment by harpocrates** [comment] 2020-04-23 15:13
Thanks for reporting! Perhaps this is a duplicate of #82?

>  I'm likely to submit more parse failures soon, is there a collection of known parse failures I could reference?

I don't think so. Whenever in doubt, just open an issue. If it is a duplicate, someone will eventually notice and close it. 😄

**Comment by shapr** [comment] 2020-04-23 15:24
Yes, at first glance this does appear to be a duplicate of #82

**Comment by nitros12** [comment] 2021-01-08 05:34
On GHC 9.0 this now only warns about the haddock comments not being associated with any item, instead of failing to parse.

```
1170.hs:13:14: warning: [-Winvalid-haddock]
    A Haddock comment cannot appear in this position and will be ignored.
   |
13 |       :: Int -- ^ first
   |              ^^^^^^^^^^

1170.hs:14:20: warning: [-Winvalid-haddock]
    Multiple Haddock comments for a single entity are not allowed.
    The extraneous comment will be ignored.
   |
14 |       -> Maybe Int -- ^ THIS FAILS
   |                    ^^^^^^^^^^^^^^^
```

**Comment by nitros12** [comment] 2021-01-12 02:02
Since #82 is tracking documenting function parameters inside records, I think it's okay to close this issue.

**Closed by nitros12** 2021-01-12 02:02 UTC
