### ISSUE TITLE
Haddock parse failure on bifunctors package

### ISSUE THREAD

**Issue by slpopejoy** [haskell/haddock#485] opened 2016-02-24 03:12 UTC
See http://hackage.haskell.org/package/bifunctors-5.2.1/reports/2
and https://github.com/ekmett/bifunctors/commit/00b941f126852754ecb4b4150829011f245347d5
Fails with following error:
```
src/Data/Bifunctor/TH.hs:675:5:
    parse error on input ‘-- * after substituting * for the dropped kind variables. If not, throw an error.’
```

I tried to reproduce the error in Parser.hs HUnits, but it doesn't reproduce:

```
      it "breaks stuff" $ do
         "* after substituting * for the dropped kind variables. If not, throw an error."
         `shouldParseTo`
          DocUnorderedList [DocParagraph (DocString "after substituting * for the dropped kind variables. If not, throw an error.")]
```
This test succeeds ... so no clue there.

Thanks,
Stuart

**Comment by bgamari** [comment] 2016-02-24 13:03
Hmm, indeed I was also unable to reproduce this locally. I wonder if this is perhaps a matter of the Hackage doc builder running an old Haddock release?

**Comment by davean** [comment] 2016-02-24 16:05
What the builder is currently running:

builder@standard-builder:~$ haddock -V
Haddock version 2.16.1, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008
builder@standard-builder:~$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.10.3
builder@standard-builder:~$ cabal -V
cabal-install version 1.22.8.0
using version 1.22.7.0 of the Cabal library

**Comment by thomie** [comment] 2016-02-24 16:30
See https://ghc.haskell.org/trac/ghc/ticket/8944
"Warn instead of stopping on misplaced Haddock comments"

Here is a reproducer, compile with `ghc -haddock`:
```
main = do
    -- * foo
    return ()
```

The parser just doesn't expect a haddock comment in that position.

This is not a regression, also happens with 7.6.3.

**Comment by slpopejoy** [comment] 2016-02-25 03:05
@thomie this is a GHC issue then, not a haddock issue?

**Comment by thomie** [comment] 2016-02-25 03:18
Yes, haddock depends on GHC's lexer and parser, and there is nothing that haddock can do to fix this. 

Since [similar bugs](https://github.com/haskell/haddock/issues/445) were closed as "not a Haddock failure", I'll close this one as well.

It just requires someone to spend a couple of days staring at GHC's parser to fix it. That someone could be you, if you're interested.

**Closed by thomie** 2016-02-25 03:18 UTC

**Comment by slpopejoy** [comment] 2016-02-25 03:22
Hmm ... it might make sense for maintainers to run 'ghc -haddock' in their CI builds so they can catch this kind of thing and at least not break hackage ...

**Comment by thomie** [comment] 2016-02-25 03:28
Yes.
