### ISSUE TITLE
Any way to indicate whether a fully qualified identifier points to a type, or a value/data constructor?

### ISSUE THREAD

**Issue by mstksg** [haskell/haddock#582] opened 2017-03-06 20:06 UTC
Hi all,

Not sure if this is the right place to ask, but I need to make a hyperlinked reference to a type in a separate module:

    See type 'Foo.Bar.MyType' for more information

But, this creates a hyperlink to the anchor for the *value* `MyType` in the documentation for module *Foo.Bar*, and not the *type* `MyType`.  In some cases, the value doesn't even exist, so the hyperlink just ignores the anchor and goes to the top of the page.

(In an unrelated issue, I'm also not sure if there's a way to distinguish between links to a type and value/constructor with the same name even unqualified, from within the same module)

Thanks!

**Comment by sjakobi** [comment] 2018-06-28 08:58
This looks like a duplicate of #667. Please re-open if it isn't.

**Closed by sjakobi** 2018-06-28 08:58 UTC

**Comment by hvr** [comment] 2018-06-28 09:06
Duplicate of #667
