### ISSUE TITLE
instance methods signature has less type variables names

### ISSUE THREAD

**Issue by paolino** [haskell/haddock#672] opened 2017-08-24 09:33 UTC
In [Data.Machine.Moore docs](https://hackage.haskell.org/package/machines-0.6.3/docs/Data-Machine-Moore.html), many methods have wrong signatures.

I.E. Applicative pure should be (and is at ghci)

> pure :: b -> Moore a b

but is reported as 

> pure :: a -> Moore a a

**Comment by alexbiehl** [comment] 2017-08-24 09:49
This is a duplicate of https://github.com/haskell/haddock/issues/613. This is already fixed in master (https://github.com/haskell/haddock/commit/4d765e3cd0a735f9a7e8d13fb6633f9ee534fbfb).

**Closed by alexbiehl** 2017-08-24 09:49 UTC
