### ISSUE TITLE
improve performance

### ISSUE THREAD

**Issue by jwaldmann** [haskell/haddock#345] opened 2014-11-10 10:53 UTC
I think haddock is taking too much time (namely, as long as a fully optimizing compilation)
See https://www.haskell.org/pipermail/haskell-cafe/2014-November/116752.html 
copied here for convenience:

I have a larg-ish project (800 modules) and these ghc compilation times:

cabal install                : 19 min
cabal install --disable-doc  : 13 min

the compilation includes the profiling build.

That is, running haddock takes the same 6 minutes
as running the compiler (with optimization)

I also built with "optimization: False library-profiling: False"
and this takes 3 min.

I understand that haddockification goes via the compiler's front-end
to resolve names and infer types. 
This takes 3 min (as the non-optimizing compiler run shows).

So, the other 3 min are unaccounted for.

(ghc-7.8.3, haddock 2.15.0, rotating disk (not SSD), Fedora 20, x86_64)

**Comment by sjakobi** [comment] 2018-07-21 14:11
Closing as a duplicate of #484.

**Closed by sjakobi** 2018-07-21 14:11 UTC
