### ISSUE TITLE
expose haddock flag to suppress/ignore haddock hide module attribute

### ISSUE THREAD

**Issue by cartazio** [haskell/haddock#751] opened 2018-02-09 19:34 UTC
for more sophisticated/power user developers who understand they're possibly getting into gritty internals, having the internal modules actually have fully rendered haddocks is super handy.

this is currently somehow possible via cabal config file at ~/.cabal/config, but not through haddock CLI as far as I can tell...

**Comment by harpocrates** [comment] 2018-02-09 19:37
Dup of https://github.com/haskell/haddock/issues/266? In any case, I agree and will implement when I get a chance.

**Comment by cartazio** [comment] 2018-02-10 15:03
Yay and thanks.  It’s also amusing that the other is a better version of
the same ticket.  And also by me :)

**Comment by harpocrates** [comment] 2018-07-01 14:18
Closing as duplicate of #266 (incidentally also resolved).

**Closed by harpocrates** 2018-07-01 14:18 UTC
