### ISSUE TITLE
no package description in cabal package index.html for 2.15.0

### ISSUE THREAD

**Issue by lspitzner** [haskell/haddock#327] opened 2014-09-17 15:10 UTC
when using "cabal haddock" with 2.14.3, the package's index.html contained the Description of the package. With 2.15.0, it does not anymore. When uploading to hackage, this seems not to matter; probably, because hackage builds its own index.html anyway (using the package metadata).

but that it works after uploading is not sufficient: i want to be able to check the package description locally _before_ uploading.

**Comment by lspitzner** [comment] 2015-01-11 18:47
This got more important again now that 2.14.3 does not work with latest ghc anymore.. :-)

1. Do you not have an example library to run haddock on? The description only refers to "libraries in Haskell Platform/on hackage", which is exactly the thing i did above. I do not even really know how to call `haddock` without using `cabal`. Could _you_ provide an example of how to run haddock for a cabal library directly?

2. Could you tag the 2.14.3 release version in the repo? It seems to be missing.

In general i think that `git bisect`ing the issue would be the more efficient path to take.

**Comment by lspitzner** [comment] 2015-01-11 22:39
ok, nevermind. tried bisecting, and more than half the commits do not compile, probably because of the required ghc version; some don't report what the requirement is, some depend on ghc-7.9.* . which commit in the ghc repository is that?

**Comment by judah** [comment] 2015-05-29 20:16
Looks like this was a laziness bug that was fixed in 2.16 by 968007937c3e108150a109c12163bbeff978629a.  I confirmed that patching that (one-character) change into 2.15 fixed the problem for me.

**Comment by Fuuzetsu** [comment] 2015-05-29 20:20
That could have done it. I'll close, thanks for confirmation.

Lazy IO strikes again.

**Closed by Fuuzetsu** 2015-05-29 20:20 UTC
