### ISSUE TITLE
Use DynFlags that suppress warnings and throw fewer errors.

### ISSUE THREAD

**Issue by duog** [haskell/haddock#623] opened 2017-05-23 18:19 UTC
I have two requests.
Firstly, I would like to disable pattern match warnings (-fwarn-incomplete-patterns et al) by default in haddock. Currently, -fno-code does not desugar code, so haddock will not produce pattern match warnings unless a package uses template haskell.
I have a ghc patch in development, https://phabricator.haskell.org/D3542, which enables desugaring for -fno-code, for the purpose of  generating more warnings and errors. However, this causes significant regressions in the haddock performance tests, due to some pathalogical pattern matches. Disabling pattern match warnings would resolve these.

Secondly, I would suggest that disabling all warnings would be a better default for haddock. I would also suggest that enabling some other flags, e.g -fdefer-type-errors would allow haddock to produce output for more packages, with no downside that I can see.

If you agree that enabling -fdefer-type-errors is a good idea, what other flags should be set? Perhaps -fdefer-typed-holes, -XPartialTypeSignatures.

I'll be happy to submit a PR if you're interested in some or all of these changes.

**Comment by alexbiehl** [comment] 2017-05-23 18:41
There are two points in this proposal: 

1. ghc-8.2 (?) will be released with `D3542` and I wouldn't want to take those regressions. Also I think `-fwarn-incomplete-patterns` doesn't do any harm for haddock generation I suppose. So lets do this.

2. As for all the other flags we should carefully sort them out, one by one looking at possible interaction with generated haddocks. For example I am not sure I want `-fdefer-type-errors` and let invalid type signatures sneak into my haddock database. But I am open for discussion.

**Comment by duog** [comment] 2017-05-23 18:45
ghc-8.2 will not have D3542, if it lands it will be in ghc-8.4.

As for 2., there are actually two sub-points. Disabling warnings, and enabling flags like -fdefer-type-errors to accept some invalid modules.

**Comment by Fuuzetsu** [comment] 2017-05-23 23:32
I think it's im best interest to stick close to flags you get during normal build. This way you don't have bad surprise when you find out that code you thought builds fine because haddock was able to get ghc to build and typecheck it is actually broken.

At the same time it seems like a abuse of functionality to me (compilation is an unwanted side effect) so I'd be OK with adding flags which speed things up as long as we document that. However that's as far as I'd go: if there is no performance benefit to a flag or the flag possibly results in failed documentation build where vanilla build works, I'm against it.

I'm ok with incomplete patterns being disabled. Need some actual motovation for other flags. defer-type-errors would not produce output for more packages or rather any extra packages it'd work for are broken to start with so have no place in being released and documentation published. If the user has a usecase for that, they can use haddock flag themselves to accomodate that. If you can show tangible benefit here for existing, working packages then maybe.

**Comment by duog** [comment] 2017-05-24 19:02
@Fuuzetsu  I absolutely agree that a documentation build should never fail when a vanilla build works.

My use case is for generating haddocks during development, where generated documentation is useful even if the package itself isn't yet.

What do you think about disabling ghc warnings while generating haddock? I consider ghc warnings during haddock generation an unwanted side effect.

I will submit a PR for disabling pattern match warnings.

**Comment by Fuuzetsu** [comment] 2017-05-24 23:12
The problem is that there is no discernible difference between "in development" and "ready" builds.

Honestly I feel like I'm yak shaving though so whatever you want is OK with me to be honest, unless someone can present an actual existing usecase they are currently depending on as counterargument.

**Comment by duog** [comment] 2017-06-03 19:03
With 628 merged, and it being clear that my other suggestions are not such great ideas and are achievable by passing flags to haddock, please feel free to close this.

**Comment by alexbiehl** [comment] 2017-06-04 07:33
Thanks again @duog!

**Closed by alexbiehl** 2017-06-04 07:33 UTC
