### ISSUE TITLE
Tooltips on hover

### ISSUE THREAD

**Issue by Rufflewind** [haskell/haddock#451] opened 2015-10-01 04:28 UTC
I think it would be useful to show a tooltip for types when the mouse is hovering over the name.  This can improve the readability of code that has lots of type synonyms (can show the expanded form in the tooltip), as well as modules that have very ambiguous names (boxed or unboxed or storable Vector?).

It could also be employed in the Source viewer, where the type of variables can be shown on hover to aid reading.

It would also be important to make the hover "sticky" enough so that the user can recursively view more and more stuff.

**Comment by timjb** [comment] 2017-09-23 21:24
Implementing this has recently gotten a lot easier with the introduction of a `doc-index.json` file that stores the definition of every ADT, type synonym, function, ... within a package.

**Comment by harpocrates** [comment] 2019-03-15 18:40
> ...modules that have very ambiguous names (boxed or unboxed or storable Vector?).

Fixed in 0bffd8bd1105331a6fcf0b7e592358c131de9300 (tooltips display module names, fixing the boxed/unboxed/storable Vector problem).

> It could also be employed in the Source viewer, where the type of variables can be shown on hover to aid reading.

Duplicate of #715, fixed in 1b26460fb3b5df5215cc1e6715661cbc7c950085.

---

I'm not sure that packing the type of identifiers into a tooltip that already includes the module name is a good idea. Types can get pretty big, so we might end up with some rather obnoxious tooltips. Feel free to re-open with a more concrete proposal though! For instance,

> It would also be important to make the hover "sticky" enough so that the user can recursively view more and more stuff.

sounds like a very interesting idea, but isn't really actionable.

**Closed by harpocrates** 2019-03-15 18:40 UTC
