### ISSUE TITLE
Haddock is putting multiline function signatures all on the same line.

### ISSUE THREAD

**Issue by locallycompact** [haskell/haddock#1248] opened 2020-11-10 22:41 UTC
Hi. I'm experiencing this behaviour here. https://hackage.haskell.org/package/polysemy-methodology-0.1.5.0/docs/Polysemy-Methodology.html

**Comment by harpocrates** [comment] 2020-11-11 01:32
Which function in particular? Note that the multiline rendering only kicks in if you documented any of the arguments.

**Comment by sjakobi** [comment] 2020-11-11 02:15
Duplicate of https://github.com/haskell/haddock/issues/147?!

#472 seems related, too.

**Comment by locallycompact** [comment] 2020-11-11 18:05
> Which function in particular? Note that the multiline rendering only kicks in if you documented any of the arguments.

Oh, I didn't know that. OK.

**Closed** 2020-11-11 18:06 UTC
