### ISSUE TITLE
Haddock renders wrong identifier: `Double` turns to `Expr`

### ISSUE THREAD

**Issue by sjakobi** [haskell/haddock#1080] opened 2019-08-19 16:59 UTC
I sadly haven't been able to make a smaller reproducer.

If I run `cabal haddock dhall` at https://github.com/dhall-lang/dhall-haskell/commit/f75d98aa9c5f119561cd9fad81dbb92c33043960 with ghc-8.6.5,

```
-- | Note that this 'Eq' instance inherits `Double`'s defects, e.g.
--
-- >>> nan = 0/0
-- >>> DoubleLit nan == DoubleLit nan
-- False
```
(from `Dhall.Core`) is rendered as

![image](https://user-images.githubusercontent.com/3664523/63284117-2d82eb80-c2b3-11e9-9ffa-f234a2480558.png)

**Comment by harpocrates** [comment] 2019-09-03 11:29
This looks like #1035 again, fixed  in b682041ed1cbeaf5aa501f85e4e46a6d2e39da3a. Definitely fixed in GHC 8.8. Just copying out the `Expr` AST and its dependent parts, note the before and after:

<img width="650" alt="Screen Shot 2019-09-03 at 7 25 53 AM" src="https://user-images.githubusercontent.com/10766081/64169726-66c36b80-ce1c-11e9-9b12-086556853fe2.png">
<img width="704" alt="Screen Shot 2019-09-03 at 7 26 07 AM" src="https://user-images.githubusercontent.com/10766081/64169730-688d2f00-ce1c-11e9-84e0-e5463418e3d7.png">

Closing as this is fixed and I think we already have our regression test case.

**Closed by harpocrates** 2019-09-03 11:29 UTC
