### ISSUE TITLE
haddock-api build fails on macOS sierra

### ISSUE THREAD

**Issue by pavelkucera** [haskell/haddock#559] opened 2016-11-06 10:59 UTC
Hi, 

For some reason, installation of haddock-api fails on my machine running macOS Sierra 10.12.1. I just made a clean installation of Haskell environment using Homebrew:

```sh
$ brew install ghc
$ brew install cabal-install
```

And then, when trying to install haddock I ran into a problem with haddock-api build. This persists even when I attempt to install only haddock api using

```
$ cabal install haddock-api
```

With output of a few warnings and three **Duplicate instance declarations** errors:

```
cabal: Entering directory '/var/folders/w3/whgjdx991_b_sd6jvsrmk7xr0000gn/T/cabal-tmp-44525/haddock-api-2.17.3'
Configuring haddock-api-2.17.3...
Building haddock-api-2.17.3...
Preprocessing library haddock-api-2.17.3...
[ 1 of 38] Compiling Paths_haddock_api ( dist/build/autogen/Paths_haddock_api.hs, dist/build/Paths_haddock_api.o )
[ 2 of 38] Compiling Haddock.Version  ( src/Haddock/Version.hs, dist/build/Haddock/Version.o )
[ 3 of 38] Compiling Haddock.Syb      ( src/Haddock/Syb.hs, dist/build/Haddock/Syb.o )
[ 4 of 38] Compiling Haddock.Parser   ( src/Haddock/Parser.hs, dist/build/Haddock/Parser.o )
[ 5 of 38] Compiling Haddock.GhcUtils ( src/Haddock/GhcUtils.hs, dist/build/Haddock/GhcUtils.o )

src/Haddock/GhcUtils.hs:20:1: warning: [-Wunused-imports]
    The import of ‘Data.Function’ is redundant
      except perhaps to import instances from ‘Data.Function’
    To import instances alone, use: import Data.Function()

src/Haddock/GhcUtils.hs:27:1: warning: [-Wunused-imports]
    The import of ‘RdrName’ is redundant
      except perhaps to import instances from ‘RdrName’
    To import instances alone, use: import RdrName()

src/Haddock/GhcUtils.hs:28:1: warning: [-Wunused-imports]
    The import of ‘GhcMonad’ is redundant
      except perhaps to import instances from ‘GhcMonad’
    To import instances alone, use: import GhcMonad()

src/Haddock/GhcUtils.hs:30:1: warning: [-Wunused-imports]
    The import of ‘UniqFM’ is redundant
      except perhaps to import instances from ‘UniqFM’
    To import instances alone, use: import UniqFM()
[ 6 of 38] Compiling Haddock.Backends.Xhtml.Types ( src/Haddock/Backends/Xhtml/Types.hs, dist/build/Haddock/Backends/Xhtml/Types.o )
[ 7 of 38] Compiling Haddock.Backends.Hyperlinker.Types ( src/Haddock/Backends/Hyperlinker/Types.hs, dist/build/Haddock/Backends/Hyperlinker/Types.o )
[ 8 of 38] Compiling Haddock.Types    ( src/Haddock/Types.hs, dist/build/Haddock/Types.o )

src/Haddock/Types.hs:451:10: error:
    Duplicate instance declarations:
      instance NFData Name -- Defined at src/Haddock/Types.hs:451:10
      instance NFData Name -- Defined in ‘Name’

src/Haddock/Types.hs:452:10: error:
    Duplicate instance declarations:
      instance NFData OccName -- Defined at src/Haddock/Types.hs:452:10
      instance NFData OccName -- Defined in ‘OccName’

src/Haddock/Types.hs:453:10: error:
    Duplicate instance declarations:
      instance NFData ModuleName
        -- Defined at src/Haddock/Types.hs:453:10
      instance NFData ModuleName -- Defined in ‘Module’
cabal: Leaving directory '/var/folders/w3/whgjdx991_b_sd6jvsrmk7xr0000gn/T/cabal-tmp-44525/haddock-api-2.17.3'
```

I'm not sure whether this is a problem of my machine and if there is a way to debug this? Has anyone run into similar issue? Any help would be appreciated.

**Comment by Miguelme** [comment] 2016-11-19 02:57
Same error in here. I tried to use all the versions available and none of them work.

**Comment by kevgathuku** [comment] 2016-11-23 11:02
Also facing the same issue here. Not sure if anyone has found a workaround yet?

**Comment by mpickering** [comment] 2016-11-23 11:39
The problem is that the homebrew installation is using a patched unofficial release of GHC and haddock hasn't been updated yet for this new release. 

@ilovezfs

**Comment by trofi** [comment] 2016-11-23 11:56
GHC 8.0.2_rc1 has the same problem. https://github.com/haskell/haddock/commit/08aa47916d6bb5a0f65d4da1021e0700b30b4b3b fixed it in master.

**Comment by ilovezfs** [comment] 2016-11-23 12:05
The brew Sierra version is nearly identical right now to 8.0.2-rc1. I recommend you apply that patch @trofi found.

**Comment by rakesh-k** [comment] 2017-03-06 15:40
Having the same problem on windows and I do have ghc 8.0.2. If the 8.0.2_rc1 has fixed the problem then I would love to apply it in my environment. Does it mean I need to download the entire source and compile myself or is there a patching command that can upgrade my ghc environment to the suggested version?

**Comment by alexbiehl** [comment] 2017-07-03 06:41
In the mean time a new haddock is released. Closing this. Feel free to reopen if you think this hasn't been addressed.

**Closed by alexbiehl** 2017-07-03 06:41 UTC
