### ISSUE TITLE
Module header not rendering correctly on hackage.haskell.org

### ISSUE THREAD

**Issue by locallycompact** [haskell/haddock#1218] opened 2020-07-26 15:01 UTC
Hi, I don't know if this is a version mismatch or I have done something wrong but the module headers as displayed here are not rendering on haskell.org in the same way as they do when I generate them via stack. The `License : MIT Stability : experimental` is for some reason displayed in the main body of the doc instead of the infobox.

http://hackage.haskell.org/package/shake-plus-0.3.1.0/docs/Development-Shake-Plus.html

**Comment by emiflake** [comment] 2021-01-05 00:42
This bug has been with Haddock since (at least) 2.18. Since 2.23.1 I can't reproduce it anymore. Looking at the diff between 2.22.0 and 2.23.1 the parser for headers has been rewritten, so I assume this fixes this behavior. haskell.org has since bumped haddock to 2.24, so it works as expected now. Closing.

**Closed by emiflake** 2021-01-05 00:42 UTC
Labels: bug:parser
