### ISSUE TITLE
Haddock to Latex fails on Data-Text-Internal

### ISSUE THREAD

**Issue by pjljvandelaar** [haskell/haddock#929] opened 2018-09-04 12:28 UTC
When I run 
` stack haddock --haddock-arguments "--latex"`
on a project that contains Data.Text (from text 1.2.3.0), I get
```
    haddock: internal error: .stack-work\dist\67675594\doc\html\text\Data-Text-Internal.tex: commitBuffer: invalid argument (invalid character)
```
after which haddock stops.

Shouldn't invalid character in packages, not be out commented or  escaped?

See also https://github.com/haskell/text/issues/233
since for me it is unclear to determine the root cause of this issue.

**Comment by harpocrates** [comment] 2018-09-04 13:16
What version of Haddock are you using? Also, what does running `locale` output on your system? I think I've got an east fix for this, but I'm still curious to replicate...

**Comment by hvr** [comment] 2018-09-04 13:31
@harpocrates yeah, I see a disturbing amount of locale-fragile `writeFile`s in haddock's codebase...

**Comment by pjljvandelaar** [comment] 2018-09-04 14:55
I tried
```
stack haddock --haddock-arguments "--version"
```
Yet, I didn't get the described behavior `Output version information and exit` as described on https://www.haskell.org/haddock/doc/html/invoking.html.

I got
```
←[0mtext-1.2.3.0: configure←[0m
←[0mtext-1.2.3.0: build←[0m
←[0mtext-1.2.3.0: haddock←[0m
Progress 1/5

--  While building custom Setup.hs for package text-1.2.3.0 using:
      C:\sr\setup-exe-cache\x86_64-windows-integersimple\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe --builddir=.stack-w
ork\dist\67675594 haddock --html --hoogle --html-location=../$pkg-$version/ --haddock-option=--hyperlinked-source --hadd
ock-option=--version
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\TorXakis\.stack-work\logs\text-1.2.3.0.log

    Configuring text-1.2.3.0...
    Preprocessing library for text-1.2.3.0..
    Building library for text-1.2.3.0..
    [ 1 of 44] Compiling Data.Text.Encoding.Error ( Data\Text\Encoding\Error.hs, .stack-work\dist\67675594\build\Data\Te
xt\Encoding\Error.o )
    [ 2 of 44] Compiling Data.Text.Internal.Builder.Int.Digits ( Data\Text\Internal\Builder\Int\Digits.hs, .stack-work\d
ist\67675594\build\Data\Text\Internal\Builder\Int\Digits.o )
    [ 3 of 44] Compiling Data.Text.Internal.Builder.RealFloat.Functions ( Data\Text\Internal\Builder\RealFloat\Functions
.hs, .stack-work\dist\67675594\build\Data\Text\Internal\Builder\RealFloat\Functions.o )
    [ 4 of 44] Compiling Data.Text.Internal.Encoding.Utf16 ( Data\Text\Internal\Encoding\Utf16.hs, .stack-work\dist\6767
5594\build\Data\Text\Internal\Encoding\Utf16.o )
    [ 5 of 44] Compiling Data.Text.Internal.Encoding.Utf32 ( Data\Text\Internal\Encoding\Utf32.hs, .stack-work\dist\6767
5594\build\Data\Text\Internal\Encoding\Utf32.o )
    [ 6 of 44] Compiling Data.Text.Internal.Functions ( Data\Text\Internal\Functions.hs, .stack-work\dist\67675594\build
\Data\Text\Internal\Functions.o )
    [ 7 of 44] Compiling Data.Text.Internal.Read ( Data\Text\Internal\Read.hs, .stack-work\dist\67675594\build\Data\Text
\Internal\Read.o )
    [ 8 of 44] Compiling Data.Text.Internal.Unsafe ( Data\Text\Internal\Unsafe.hs, .stack-work\dist\67675594\build\Data\
Text\Internal\Unsafe.o )
    [ 9 of 44] Compiling Data.Text.Internal.Unsafe.Shift ( Data\Text\Internal\Unsafe\Shift.hs, .stack-work\dist\67675594
\build\Data\Text\Internal\Unsafe\Shift.o )
    [10 of 44] Compiling Data.Text.Array  ( Data\Text\Array.hs, .stack-work\dist\67675594\build\Data\Text\Array.o )
    [11 of 44] Compiling Data.Text.Internal.Unsafe.Char ( Data\Text\Internal\Unsafe\Char.hs, .stack-work\dist\67675594\b
uild\Data\Text\Internal\Unsafe\Char.o )
    [12 of 44] Compiling Data.Text.Internal.Encoding.Utf8 ( Data\Text\Internal\Encoding\Utf8.hs, .stack-work\dist\676755
94\build\Data\Text\Internal\Encoding\Utf8.o )
    [13 of 44] Compiling Data.Text.Internal ( Data\Text\Internal.hs, .stack-work\dist\67675594\build\Data\Text\Internal.
o )
    [14 of 44] Compiling Data.Text.Internal.Search ( Data\Text\Internal\Search.hs, .stack-work\dist\67675594\build\Data\
Text\Internal\Search.o )
    [15 of 44] Compiling Data.Text.Internal.Fusion.Size ( Data\Text\Internal\Fusion\Size.hs, .stack-work\dist\67675594\b
uild\Data\Text\Internal\Fusion\Size.o )
    [16 of 44] Compiling Data.Text.Internal.Fusion.Types ( Data\Text\Internal\Fusion\Types.hs, .stack-work\dist\67675594
\build\Data\Text\Internal\Fusion\Types.o )
    [17 of 44] Compiling Data.Text.Internal.Fusion.CaseMapping ( Data\Text\Internal\Fusion\CaseMapping.hs, .stack-work\d
ist\67675594\build\Data\Text\Internal\Fusion\CaseMapping.o )
    [18 of 44] Compiling Data.Text.Internal.Fusion.Common ( Data\Text\Internal\Fusion\Common.hs, .stack-work\dist\676755
94\build\Data\Text\Internal\Fusion\Common.o )
    [19 of 44] Compiling Data.Text.Unsafe ( Data\Text\Unsafe.hs, .stack-work\dist\67675594\build\Data\Text\Unsafe.o )
    [20 of 44] Compiling Data.Text.Internal.Private ( Data\Text\Internal\Private.hs, .stack-work\dist\67675594\build\Dat
a\Text\Internal\Private.o )
    [21 of 44] Compiling Data.Text.Internal.Fusion ( Data\Text\Internal\Fusion.hs, .stack-work\dist\67675594\build\Data\
Text\Internal\Fusion.o )
    [22 of 44] Compiling Data.Text.Show   ( Data\Text\Show.hs, .stack-work\dist\67675594\build\Data\Text\Show.o )
    [23 of 44] Compiling Data.Text.Internal.Encoding.Fusion.Common ( Data\Text\Internal\Encoding\Fusion\Common.hs, .stac
k-work\dist\67675594\build\Data\Text\Internal\Encoding\Fusion\Common.o )
    [24 of 44] Compiling Data.Text.Internal.Lazy.Encoding.Fusion ( Data\Text\Internal\Lazy\Encoding\Fusion.hs, .stack-wo
rk\dist\67675594\build\Data\Text\Internal\Lazy\Encoding\Fusion.o )
    [25 of 44] Compiling Data.Text.Internal.Encoding.Fusion ( Data\Text\Internal\Encoding\Fusion.hs, .stack-work\dist\67
675594\build\Data\Text\Internal\Encoding\Fusion.o )
    [26 of 44] Compiling Data.Text.Encoding ( Data\Text\Encoding.hs, .stack-work\dist\67675594\build\Data\Text\Encoding.
o )
    [27 of 44] Compiling Data.Text.Foreign ( Data\Text\Foreign.hs, .stack-work\dist\67675594\build\Data\Text\Foreign.o )

    [28 of 44] Compiling Data.Text        ( Data\Text.hs, .stack-work\dist\67675594\build\Data\Text.o )
    [29 of 44] Compiling Data.Text.Read   ( Data\Text\Read.hs, .stack-work\dist\67675594\build\Data\Text\Read.o )
    [30 of 44] Compiling Data.Text.Internal.Lazy ( Data\Text\Internal\Lazy.hs, .stack-work\dist\67675594\build\Data\Text
\Internal\Lazy.o )
    [31 of 44] Compiling Data.Text.Lazy.Internal ( Data\Text\Lazy\Internal.hs, .stack-work\dist\67675594\build\Data\Text
\Lazy\Internal.o )
    [32 of 44] Compiling Data.Text.Internal.Lazy.Search ( Data\Text\Internal\Lazy\Search.hs, .stack-work\dist\67675594\b
uild\Data\Text\Internal\Lazy\Search.o )
    [33 of 44] Compiling Data.Text.Internal.Lazy.Fusion ( Data\Text\Internal\Lazy\Fusion.hs, .stack-work\dist\67675594\b
uild\Data\Text\Internal\Lazy\Fusion.o )
    [34 of 44] Compiling Data.Text.Lazy.Encoding ( Data\Text\Lazy\Encoding.hs, .stack-work\dist\67675594\build\Data\Text
\Lazy\Encoding.o )
    [35 of 44] Compiling Data.Text.Lazy   ( Data\Text\Lazy.hs, .stack-work\dist\67675594\build\Data\Text\Lazy.o )
    [36 of 44] Compiling Data.Text.Lazy.Read ( Data\Text\Lazy\Read.hs, .stack-work\dist\67675594\build\Data\Text\Lazy\Re
ad.o )
    [37 of 44] Compiling Data.Text.Internal.IO ( Data\Text\Internal\IO.hs, .stack-work\dist\67675594\build\Data\Text\Int
ernal\IO.o )
    [38 of 44] Compiling Data.Text.Internal.Builder ( Data\Text\Internal\Builder.hs, .stack-work\dist\67675594\build\Dat
a\Text\Internal\Builder.o )
    [39 of 44] Compiling Data.Text.Lazy.Builder ( Data\Text\Lazy\Builder.hs, .stack-work\dist\67675594\build\Data\Text\L
azy\Builder.o )
    [40 of 44] Compiling Data.Text.Internal.Builder.Functions ( Data\Text\Internal\Builder\Functions.hs, .stack-work\dis
t\67675594\build\Data\Text\Internal\Builder\Functions.o )
    [41 of 44] Compiling Data.Text.Lazy.Builder.Int ( Data\Text\Lazy\Builder\Int.hs, .stack-work\dist\67675594\build\Dat
a\Text\Lazy\Builder\Int.o )

    ←[;1mData\Text\Lazy\Builder\Int.hs:42:1: ←[;1m←[35mwarning:←[0m←[0m←[;1m [←[;1m←[35m-Wunused-imports←[0m←[0m←[;1m]←[
0m←[0m←[;1m
        The import of `GHC.Integer' is redundant
          except perhaps to import instances from `GHC.Integer'
        To import instances alone, use: import GHC.Integer()←[0m←[0m
    ←[;1m←[34m   |←[0m←[0m
    ←[;1m←[34m42 |←[0m←[0m ←[;1m←[35mimport GHC.Integer←[0m←[0m
    ←[;1m←[34m   |←[0m←[0m←[;1m←[35m ^^^^^^^^^^^^^^^^^^←[0m←[0m
    ←[0m←[0m←[0m[42 of 44] Compiling Data.Text.Lazy.Builder.RealFloat ( Data\Text\Lazy\Builder\RealFloat.hs, .stack-work
\dist\67675594\build\Data\Text\Lazy\Builder\RealFloat.o )
    [43 of 44] Compiling Data.Text.IO     ( Data\Text\IO.hs, .stack-work\dist\67675594\build\Data\Text\IO.o )
    [44 of 44] Compiling Data.Text.Lazy.IO ( Data\Text\Lazy\IO.hs, .stack-work\dist\67675594\build\Data\Text\Lazy\IO.o )

    Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe: Could not get GHC version from
    Haddock
PS C:\TorXakis>
```

**Comment by pjljvandelaar** [comment] 2018-09-04 15:01
Also in a simple project I don't get a version number:

```
PS C:\experiment> stack haddock --haddock-arguments "--version"
←[0mBuilding all executables for `experiment' once. After a successful build of all of them, only specified executables
will be rebuilt.←[0m
←[0mexperiment-0.2.1.0: configure (exe)←[0m
←[0mConfiguring experiment-0.2.1.0...←[0m
←[0mWarning: The 'license-file' field refers to the file 'license.txt' which does←[0m
←[0mnot exist.←[0m
←[0mexperiment-0.2.1.0: build (exe)←[0m
←[0mPreprocessing executable 'experiment' for experiment-0.2.1.0..←[0m
←[0mBuilding executable 'experiment' for experiment-0.2.1.0..←[0m
←[0m[1 of 1] Compiling Main             ( src\Experiment.hs, .stack-work\dist\5c8418a7\build\experiment\experiment-tmp\M
ain.o )←[0m
←[0mLinking .stack-work\dist\5c8418a7\build\experiment\experiment.exe ...←[0m
←[0mexperiment-0.2.1.0: copy/register←[0m
←[0mlicense.txt: copyFile: does not exist (No such file or directory)←[0m
←[0mUpdating Haddock index for snapshot packages in
C:\sr\snapshots\8f29239e\doc\index.html←[0m
```

**Comment by harpocrates** [comment] 2018-09-04 15:02
> Yet, I didn't get the described behavior Output version information and exit as described on https://www.haskell.org/haddock/doc/html/invoking.html.

That's because you aren't calling Haddock, you are calling Stack, which calls Cabal-the-library, which calls Haddock. I'm unfamiliar with how Stack users generally get the version of Haddock. Perhaps the Stack folks would know this better?

**Comment by pjljvandelaar** [comment] 2018-09-04 15:03
Asking stack to install haddock yields

```
PS C:\> stack install haddock
←[0m
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for haddock-2.20.0:
    base-4.10.1.0 from stack configuration does not match ^>=4.11.0  (latest matching version
                  is 4.11.1.0)
    haddock-api must match ==2.20.0, but the stack configuration has no specified version  (latest
                matching version is 2.20.0)
needed since haddock is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some
    working build configuration. This can be convenient when dealing with many complicated
    constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps
    in C:\sr\global-project\stack.yaml:

- base-4.11.1.0
- haddock-api-2.20.0
←[0m
Plan construction failed.
PS C:\>
```

So it seems version 2.20.0

**Comment by harpocrates** [comment] 2018-09-04 15:10
You've just tried to install `haddock` from Stack as a regular Haskell program - that doesn't say much. Stack already has (probably) several Haddock binaries that it is making available to Cabal when you call `stack haddock` (just the same way it has several GHC binaries). That said, I'm ill-equipped to help you here - I'm not familiar with how Stack works.

Also, what is the output of `locale` on your system?

**Comment by pjljvandelaar** [comment] 2018-09-04 15:19
I am working on windows.
My `locale` is English (United States)
![locale](https://user-images.githubusercontent.com/18348654/45040570-d8c07380-b055-11e8-9bca-600111a90dcc.jpg)

**Comment by harpocrates** [comment] 2018-09-04 15:28
What is the output of the following?

```
$ ghci       # Or however you get to GHCi from inside your project
ghci> import GHC.IO.Encoding
Prelude GHC.IO.Encoding> getLocaleEncoding
```

**Comment by pjljvandelaar** [comment] 2018-09-04 18:06
Tomorrow not in the office. Will report it Thursday.

**Comment by pjljvandelaar** [comment] 2018-09-06 08:55
started ghci using `stack ghci` 
`getLocaleEncoding` yields `CP437`

**Comment by harpocrates** [comment] 2018-09-18 01:10
Even with the UTF-8 encoding fix, the generated docs for `text` still fail to build.

Forthcoming fix in https://github.com/harpocrates/haddock/tree/latex-improvements (needs to be applied on top of Hi Haddock stuff).

**Comment by harpocrates** [comment] 2019-05-27 19:43
I've confirmed that on the `ghc-8.8` branch, Haddock with `--latex` successfully runs on `text` and the generated `.tex` files can successfully be compiled into a PDF.

**Closed by harpocrates** 2019-05-27 19:43 UTC
Labels: bug
