### ISSUE TITLE
Type variables from instances and class functions are conflated

### ISSUE THREAD

**Issue by endgame** [haskell/haddock#654] opened 2017-07-13 23:51 UTC
GHC Version: 8.0.2
Haddock Version: 2.17.3
Minimal Example:
```haskell
import Prelude hiding (Functor)

class Functor f where
    fmap :: (a -> b) -> f a -> f b

instance Functor (Either a) where
    fmap _ (Left x) = Left x
    fmap f (Right a) = Right $ f a
```

Expand the instance declaration for `Either` and note that it's conflated the `a` from the `instance` with the `a` from the type signature of `fmap`, which makes it look like a more restrictive type than it really is.

![haddock](https://user-images.githubusercontent.com/231483/28192455-9c4ed2b8-6879-11e7-9ac4-bcf9e65a457f.png)

**Comment by RyanGlScott** [comment] 2017-08-02 15:54
I believe this is a duplicate of #613.

**Comment by alexbiehl** [comment] 2017-08-02 16:51
Yes, you are right, closing this in favour of #613 .

**Closed by alexbiehl** 2017-08-02 16:51 UTC
