### ISSUE TITLE
Synopsis popup in Windows 10 Chrome and Firefox doesn’t scroll

### ISSUE THREAD

**Issue by acapi** [haskell/haddock#1079] opened 2019-08-19 15:00 UTC
The Synopsis popup of LIBRARIES doesn’t scroll in fully updated Chrome and Firefox (Windows 10), while in Edge it’s all ok (vertical and horizontal scroll).

I tried to post this problem to libraries@haskell.org, but the server replied: "You are not allowed to post to this mailing list, and your message has been automatically rejected."

Question 1: Is it caused by incorrect browsers setting? Question 2: It is not the first time that I detect those that seem to me errors or typos. How can you report them to those in charge?

**Comment by harpocrates** [comment] 2019-08-19 15:11
Thanks for reporting!

I think this will be fixed with the release of GHC 8.8.  You should be able to see the release candidate docs here: https://downloads.haskell.org/ghc/8.8.1-rc1/docs/html/libraries/base-4.13.0.0/Prelude.html. Could you double check if the problem is still present there?

> Question 1: Is it caused by incorrect browsers setting?

Probably not.

> Question 2: It is not the first time that I detect those that seem to me errors or typos. How can you report them to those in charge?

Typos in actual docs should be reported to the source repository. Usually, the `Maintainer` field in the Haddocks is the address to send to. I'm not sure why `base` has libraries@haskell.org as the maintainer, and why that address is not an open mailing list. For `base`, open an issue at https://gitlab.haskell.org/ghc/ghc/issues.

Errors pertaining to the HTML structure (like the one for the synopsis), belong on this issue tracker. 😄

**Comment by acapi** [comment] 2019-08-19 15:35
Thanks for your answers Alec,

I’ve just checked that the synopsis problem is fixed in the release candidate which is available by following your link.

Regards

Alberto Capitani

Da: Alec Theriault <notifications@github.com>
Inviato: lunedì 19 agosto 2019 17:12
A: haskell/haddock <haddock@noreply.github.com>
Cc: acapi <alberto.capitani@hotmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [haskell/haddock] Synopsis popup in Windows 10 Chrome and Firefox doesn’t scroll (#1079)


Thanks for reporting!

I think this will be fixed with the release of GHC 8.8. You should be able to see the release candidate docs here: https://downloads.haskell.org/ghc/8.8.1-rc1/docs/html/libraries/base-4.13.0.0/Prelude.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownloads.haskell.org%2Fghc%2F8.8.1-rc1%2Fdocs%2Fhtml%2Flibraries%2Fbase-4.13.0.0%2FPrelude.html&data=02%7C01%7C%7C3a1d4ce5069d48bf92cf08d724b78589%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637018242939273599&sdata=FubGhje7Y%2FX4ZwX3uLB3JR1k5L%2FvAI1kQ9pwQ8ntRr0%3D&reserved=0>. Could you double check if the problem is still present there?

Question 1: Is it caused by incorrect browsers setting?

Probably not.

Question 2: It is not the first time that I detect those that seem to me errors or typos. How can you report them to those in charge?

Typos in actual docs should be reported to the source repository. Usually, the Maintainer field in the Haddocks is the address to send to. I'm not sure why base has libraries@haskell.org<mailto:libraries@haskell.org> as the maintainer, and why that address is not an open mailing list. For base, open an issue at https://gitlab.haskell.org/ghc/ghc/issues<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgitlab.haskell.org%2Fghc%2Fghc%2Fissues&data=02%7C01%7C%7C3a1d4ce5069d48bf92cf08d724b78589%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637018242939283604&sdata=9g9M1PKc%2BX8k3y3DlOuxZO7YwXegkirqV2xejBkFS%2FE%3D&reserved=0>.

Errors pertaining to the HTML structure (like the one for the synopsis), belong on this issue tracker. 😄

**Closed** 2019-09-16 01:38 UTC
